export default [
  {
    id: 4444,
    owner: 5550,
    model: 'RAV 4',
    manufacturer: 'Toyota',
    imageUrl: 'My Image url from cloudinary',
    imageName: 'my_redcar.png',
    transmission: 'Automatic',
    year: 2011,
    fuelType: 'Fuel',
    bodyType: 'Suv',
    state: 'new',
    price: 4700000,
    status: 'sold',
    description:
      'car ac still intact, alloy rims, perfect for travel with family',
    createdOn: new Date(),
  },
  {
    id: 25553,
    owner: 1277,
    model: 'Corolla Sport',
    manufacturer: 'Toyota',
    imageUrl: 'A url from cloudinary',
    imageName: 'my_toyoyta.png',
    transmission: 'Automatic',
    year: 2006,
    fuelType: 'Fuel',
    bodyType: 'Sedan',
    state: 'used',
    price: 1400000,
    status: 'unsold',
    description: 'leather interior based on factory fittings',
    createdOn: new Date(),
  },
  {
    id: 11223,
    owner: 27455,
    model: 'C 300',
    manufacturer: 'Mercedez',
    imageUrl: 'Cloudinary api',
    imageName: 'my_benz.png',
    transmission: 'Automatic',
    year: 2008,
    fuelType: 'Fuel',
    bodyType: 'Sedan',
    state: 'used',
    price: 2000000,
    status: 'unsold',
    description: 'Alloy rims, still on highway excellent ',
    createdOn: new Date(),
  },
];
